#!/bin/bash
# ============================================================
# Script 1: System Identity Report
# This script displays system details like username, hostname and OS info
# Created by Roopsha for Linux project
# Author: [Your Name] | Reg No: [Your Registration Number]
# Course: Open Source Software | OSS NGMC Capstone Project
# Description: Displays a welcome screen with system info
#              and open-source license details for the OS.
# ============================================================

# --- Student & Software Variables ---
STUDENT_NAME="Roopsha Ghosh"
SOFTWARE_CHOICE="Git"
REG_NO="24BCE10292"

# --- Gather System Information using command substitution ---
KERNEL=$(uname -r)                          # Kernel version
DISTRO=$(cat /etc/os-release | grep "^PRETTY_NAME" | cut -d= -f2 | tr -d '"')  # Distro name
CURRENT_NAME=$(whoami)                         # Logged-in user
HOME_DIR=$HOME                             # User's home directory
UPTIME=$(uptime -p)                         # System uptime in human-readable form
CURRENT_DATE=$(date '+%A, %d %B %Y')        # Full date (e.g., Monday, 01 January 2024)
CURRENT_TIME=$(date '+%H:%M:%S %Z')         # Current time with timezone
IP_ADDRESS=$(hostname -I | awk '{print $1}')  #display ip address
CPU_INFO=$(lscpu | grep "Model name" | cut -d: -f2)  #cpu info

# --- Determine OS License ---
# Most Linux distributions are licensed under GPL v2 or compatible licenses
# The Linux kernel itself is licensed under GPL v2
OS_LICENSE="GNU General Public License v2 (GPL v2)"

# ============================================================
# Display: Open Source Audit Welcome Screen
# ============================================================
echo "================================================================"
echo "        OPEN SOURCE AUDIT — LINUX SYSTEM ANALYSIS REPORT             "
echo "================================================================"
echo ""
echo "  Student  : $STUDENT_NAME"
echo "  Software : $SOFTWARE_CHOICE"
echo "  Reg No   : $REG_NO"
echo ""
echo "==============================================================="
echo "  SYSTEM INFORMATION "
echo "==============================================================="
echo "  Distribution : $DISTRO"
echo "  Kernel       : $KERNEL"
echo "  Active User  : $CURRENT_NAME"
echo "  Home Dir     : $HOME_DIR"
echo "  Uptime       : $UPTIME"
echo "  Date         : $CURRENT_DATE"
echo "  Time         : $CURRENT_TIME"
echo "  IP Address   : $IP_ADDRESS"
echo "  CPU Info     : $CPU_INFO"
echo ""
echo "==============================================================="
echo "  LICENSE INFORMATION"
echo "==============================================================="
echo "This system operates under the open-source license:"
echo "  $OS_LICENSE"
echo ""
echo "  The GPL v2 ensures that the OS kernel source code is freely"
echo "  available, modifiable, and redistributable — as long as any"
echo "  derivative work is also distributed under the same license."
echo "---------------------------------------------------------------"
echo "  Report Generated By : $STUDENT_NAME"
echo "  Thank you!"
echo "==============================================================="
